# .github/workflows/flutter-ci.yml

name: CI - Fase 1 - Testes Unitários

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  unit-tests:
    name: Unit & Widget Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Instalar Dependências
        run: flutter pub get

      - name: Rodar Testes Unitários e de Widget
        run: flutter test

      - name: Post Instruction Comment
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Testes unitários passaram com sucesso!\n\n**Opcional:** Para rodar a suíte completa de testes de integração no Jenkins, comente nesta PR com a palavra-chave: `Erebor-CI`'
            })